# file: roles/common/tasks/main.yml
---
- name: Update system
  yum: name=* state=latest update_cache=yes

- name: Install common utils
  yum: name={{item}} state=present
  with_items: "{{ common_packages }}"


- name: Disable SELinux
  selinux: policy=targeted state=permissive

- name: Disable Firewall
  service: name=firewalld state=stopped enabled=no
