# file: roles/docker/tasks/main.yml
---
- name: Get Docker Binary
  get_url: url={{docker_url}} dest=/usr/bin/docker mode=0755

- name: Create Docker group
  group: name={{docker_group}} state=present

- name: Add Vagrant User to Docker group
  user: name={{ansible_ssh_user}} groups={{docker_group}} append=yes

- name: Docker Socket service
  template: src=docker.socket.j2 dest=/usr/lib/systemd/system/docker.socket
  notify:
    - reload systemd
    - restart docker socket

- name: Docker service
  template: src=docker.service.j2 dest=/usr/lib/systemd/system/docker.service
  notify:
    - reload systemd
    - restart docker service

- name: Docker sysconfig
  template: src=docker.sysconfig.j2 dest=/etc/sysconfig/docker
  notify: restart docker service

- name: Get Docker-Compose Binary
  get_url: url=https://github.com/docker/compose/releases/download/1.5.2/docker-compose-{{ansible_system}}-{{ansible_architecture}} dest=/usr/bin/docker-compose mode=0755
